In [1]:
import pandas as pd
import numpy as np

data= pd.read_csv(r"C:\Users\saras\Documents\School\STA 6704- Data Mining 2\widsdatathon2020\training_v2.csv")
data.head()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.73,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.42,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.95,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.64,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma

In [2]:
#Finding the total number of rows in the dataset
row=data.shape[0]
row

91713

In [3]:
#Checking the missing values in the dataset
data.isnull().sum()
#No missing values in the target variable hospital_death

encounter_id                      0
patient_id                        0
hospital_id                       0
hospital_death                    0
age                            4228
                               ...
leukemia                        715
lymphoma                        715
solid_tumor_with_metastasis     715
apache_3j_bodysystem           1662
apache_2_bodysystem            1662
Length: 186, dtype: int64

In [4]:
#Dropping the columns with more than 50% missing values
data_new=data[data.columns[data.isnull().sum()<(0.15*row)]]
data_new.head()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.73,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.42,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.95,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.64,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma

In [5]:
data_new.shape

(91713, 102)

In [6]:
#Finding columns with categorical variables
cat=data_new.select_dtypes(include=['object']).columns.tolist()
#Checking if there are any missing values in the categorical variables
data_new[cat].isnull().sum()

ethnicity               1395
gender                    25
icu_admit_source         112
icu_stay_type              0
icu_type                   0
apache_3j_bodysystem    1662
apache_2_bodysystem     1662
dtype: int64

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
#Imputing missing values for all the categorical variables
for col in cat:
    data_new[col]= data[col].fillna(data[col].mode()[0])
data_new[cat].isnull().sum()

ethnicity               0
gender                  0
icu_admit_source        0
icu_stay_type           0
icu_type                0
apache_3j_bodysystem    0
apache_2_bodysystem     0
dtype: int64

In [9]:
missing= data_new.columns[data_new.isnull().sum()>0]
missing

Index(['age', 'bmi', 'height', 'weight', 'apache_2_diagnosis',
       'apache_3j_diagnosis', 'arf_apache', 'gcs_eyes_apache',
       'gcs_motor_apache', 'gcs_unable_apache', 'gcs_verbal_apache',
       'glucose_apache', 'heart_rate_apache', 'intubated_apache', 'map_apache',
       'resprate_apache', 'temp_apache', 'ventilated_apache', 'd1_diasbp_max',
       'd1_diasbp_min', 'd1_diasbp_noninvasive_max',
       'd1_diasbp_noninvasive_min', 'd1_heartrate_max', 'd1_heartrate_min',
       'd1_mbp_max', 'd1_mbp_min', 'd1_mbp_noninvasive_max',
       'd1_mbp_noninvasive_min', 'd1_resprate_max', 'd1_resprate_min',
       'd1_spo2_max', 'd1_spo2_min', 'd1_sysbp_max', 'd1_sysbp_min',
       'd1_sysbp_noninvasive_max', 'd1_sysbp_noninvasive_min', 'd1_temp_max',
       'd1_temp_min', 'h1_diasbp_max', 'h1_diasbp_min',
       'h1_diasbp_noninvasive_max', 'h1_diasbp_noninvasive_min',
       'h1_heartrate_max', 'h1_heartrate_min', 'h1_mbp_max', 'h1_mbp_min',
       'h1_mbp_noninvasive_max', 'h1_mbp_noninvasive_min', 'h1_resprate_max',
       'h1_resprate_min', 'h1_spo2_max', 'h1_spo2_min', 'h1_sysbp_max',
       'h1_sysbp_min', 'h1_sysbp_noninvasive_max', 'h1_sysbp_noninvasive_min',
       'd1_bun_max', 'd1_bun_min', 'd1_calcium_max', 'd1_calcium_min',
       'd1_creatinine_max', 'd1_creatinine_min', 'd1_glucose_max',
       'd1_glucose_min', 'd1_hemaglobin_max', 'd1_hemaglobin_min',
       'd1_hematocrit_max', 'd1_hematocrit_min', 'd1_platelets_max',
       'd1_platelets_min', 'd1_potassium_max', 'd1_potassium_min',
       'd1_sodium_max', 'd1_sodium_min', 'd1_wbc_max', 'd1_wbc_min',
       'apache_4a_hospital_death_prob', 'apache_4a_icu_death_prob', 'aids',
       'cirrhosis', 'diabetes_mellitus', 'hepatic_failure',
       'immunosuppression', 'leukemia', 'lymphoma',
       'solid_tumor_with_metastasis'],
      dtype='object')

In [10]:
#Dropping all non-invasive measurements
data_new= data_new[data_new.columns.drop(list(data_new.filter(regex='noninvasive')))]
data_new

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal

In [11]:
missing= data_new.columns[data_new.isnull().sum()>0]
missing

Index(['age', 'bmi', 'height', 'weight', 'apache_2_diagnosis',
       'apache_3j_diagnosis', 'arf_apache', 'gcs_eyes_apache',
       'gcs_motor_apache', 'gcs_unable_apache', 'gcs_verbal_apache',
       'glucose_apache', 'heart_rate_apache', 'intubated_apache', 'map_apache',
       'resprate_apache', 'temp_apache', 'ventilated_apache', 'd1_diasbp_max',
       'd1_diasbp_min', 'd1_heartrate_max', 'd1_heartrate_min', 'd1_mbp_max',
       'd1_mbp_min', 'd1_resprate_max', 'd1_resprate_min', 'd1_spo2_max',
       'd1_spo2_min', 'd1_sysbp_max', 'd1_sysbp_min', 'd1_temp_max',
       'd1_temp_min', 'h1_diasbp_max', 'h1_diasbp_min', 'h1_heartrate_max',
       'h1_heartrate_min', 'h1_mbp_max', 'h1_mbp_min', 'h1_resprate_max',
       'h1_resprate_min', 'h1_spo2_max', 'h1_spo2_min', 'h1_sysbp_max',
       'h1_sysbp_min', 'd1_bun_max', 'd1_bun_min', 'd1_calcium_max',
       'd1_calcium_min', 'd1_creatinine_max', 'd1_creatinine_min',
       'd1_glucose_max', 'd1_glucose_min', 'd1_hemaglobin_max',
       'd1_hemaglobin_min', 'd1_hematocrit_max', 'd1_hematocrit_min',
       'd1_platelets_max', 'd1_platelets_min', 'd1_potassium_max',
       'd1_potassium_min', 'd1_sodium_max', 'd1_sodium_min', 'd1_wbc_max',
       'd1_wbc_min', 'apache_4a_hospital_death_prob',
       'apache_4a_icu_death_prob', 'aids', 'cirrhosis', 'diabetes_mellitus',
       'hepatic_failure', 'immunosuppression', 'leukemia', 'lymphoma',
       'solid_tumor_with_metastasis'],
      dtype='object')

'apache_2_diagnosis'- Mode 
apache_3j_diagnosis- Mode
arf_apache- Mode
gcs_eyes_apache- Mode
gcs_motor_apache- Mode
gcs_unable_apache - Mode
gcs_verbal_apache- Mode
glucose_apache- Round value of mean
heart_rate_apache- Round value of mean
intubated_apache- Mode
map_apache- Round value of mean
resprate_apache- Mean
temp_apache- Mean
ventilated_apache- Mode
d1_diasbp_max,h1_diasbp_max- Round value of mean
d1_diasbp_min,h1_diasbp_min- Round value of mean
d1_heartrate_max,h1_heartrate_max- Round value of mean
d1_heartrate_min,h1_heartrate_min- Round value of mean
d1_mbp_max,h1_mbp_max- Round value of mean
d1_mbp_min,h1_mbp_min-  Round value of mean
d1_resprate_max,h1_resprate_max- Round value of mean
d1_resprate_min,h1_resprate_min - Round value of mean
d1_spo2_max,h1_spo2_max- Round value of mean
d1_spo2_min,h1_spo2_min- Round value of mean
d1_sysbp_max,h1_sysbp_max - Round value of mean
d1_sysbp_min,h1_sysbp_min- Round value of mean
d1_temp_max- Mean
d1_temp_min- Mean
d1_bun_max,d1_bun_min- Mean
d1_calcium_max, d1_calcium_min - Mean
d1_creatinine_max, d1_creatinine_min- Mean
d1_glucose_max,d1_glucose_min- Round value of mean
d1_hemaglobin_max, d1_hemaglobin_min- Mean
d1_hematocrit_max, d1_hematocrit_min- Mean
d1_platelets_max, d1_platelets_min- Round of mean
    d1_potassium_max, d1_potassium_min- Mean
d1_wbc_max,d1_wbc_min- Mean
apache_4a_hospital_death_prob- Mean
aids, cirrhosis, diabetes_mellitus, hepatic_failure, leukemia, lymphoma, solid_tumor_with_metastasis- Mode

In [12]:
col_mode= ['apache_2_diagnosis',
'apache_3j_diagnosis',
'arf_apache',
'gcs_eyes_apache',
'gcs_motor_apache',
'gcs_unable_apache',
'gcs_verbal_apache',
'intubated_apache',
'ventilated_apache',
'aids',
'cirrhosis',
'diabetes_mellitus',
'hepatic_failure',
'leukemia',
'lymphoma',
'solid_tumor_with_metastasis','immunosuppression']
for col in col_mode:
    data_new[col]= data_new[col].fillna(data[col].mode()[0])
data_new[col_mode].isnull().sum()

apache_2_diagnosis             0
apache_3j_diagnosis            0
arf_apache                     0
gcs_eyes_apache                0
gcs_motor_apache               0
gcs_unable_apache              0
gcs_verbal_apache              0
intubated_apache               0
ventilated_apache              0
aids                           0
cirrhosis                      0
diabetes_mellitus              0
hepatic_failure                0
leukemia                       0
lymphoma                       0
solid_tumor_with_metastasis    0
immunosuppression              0
dtype: int64

In [13]:
col_mean= ['resprate_apache',
'temp_apache',
'd1_temp_max',
'd1_temp_min',
'd1_bun_max',
'd1_bun_min',
'd1_calcium_max',
'd1_calcium_min',
'd1_creatinine_max',
'd1_creatinine_min',
'd1_hemaglobin_max',
'd1_hemaglobin_min',
'd1_hematocrit_max',
'd1_hematocrit_min',
'd1_potassium_max',
'd1_potassium_min',
'd1_wbc_max',
'd1_wbc_min','d1_calcium_max', 'd1_calcium_min','d1_sodium_min','d1_sodium_max']
for col in col_mean:
    data_new[col]= data_new[col].fillna(data[col].mean())
data_new[col_mean].isnull().sum()

resprate_apache      0
temp_apache          0
d1_temp_max          0
d1_temp_min          0
d1_bun_max           0
d1_bun_min           0
d1_calcium_max       0
d1_calcium_min       0
d1_creatinine_max    0
d1_creatinine_min    0
d1_hemaglobin_max    0
d1_hemaglobin_min    0
d1_hematocrit_max    0
d1_hematocrit_min    0
d1_potassium_max     0
d1_potassium_min     0
d1_wbc_max           0
d1_wbc_min           0
d1_calcium_max       0
d1_calcium_min       0
d1_sodium_min        0
d1_sodium_max        0
dtype: int64

In [14]:
col_roundmean= ['glucose_apache',
'map_apache',
'd1_diasbp_max',
'h1_diasbp_max',
'd1_diasbp_min',
'h1_diasbp_min',
'd1_heartrate_max',
'h1_heartrate_max',
'd1_heartrate_min',
'h1_heartrate_min',
'd1_mbp_max',
'h1_mbp_max',
'd1_mbp_min',
'h1_mbp_min',
'd1_resprate_max',
'h1_resprate_max',
'd1_resprate_min',
'h1_resprate_min',
'd1_spo2_max',
'h1_spo2_max',
'd1_spo2_min',
'h1_spo2_min',
'd1_sysbp_max',
'h1_sysbp_max',
'd1_sysbp_min',
'h1_sysbp_min',
'd1_glucose_max',
'd1_glucose_min',
'd1_platelets_max',
'd1_platelets_min','heart_rate_apache']
for col in col_roundmean:
    data_new[col]= data_new[col].fillna(int(data[col].mean()))
data_new[col_roundmean].isnull().sum()

glucose_apache       0
map_apache           0
d1_diasbp_max        0
h1_diasbp_max        0
d1_diasbp_min        0
h1_diasbp_min        0
d1_heartrate_max     0
h1_heartrate_max     0
d1_heartrate_min     0
h1_heartrate_min     0
d1_mbp_max           0
h1_mbp_max           0
d1_mbp_min           0
h1_mbp_min           0
d1_resprate_max      0
h1_resprate_max      0
d1_resprate_min      0
h1_resprate_min      0
d1_spo2_max          0
h1_spo2_max          0
d1_spo2_min          0
h1_spo2_min          0
d1_sysbp_max         0
h1_sysbp_max         0
d1_sysbp_min         0
h1_sysbp_min         0
d1_glucose_max       0
d1_glucose_min       0
d1_platelets_max     0
d1_platelets_min     0
heart_rate_apache    0
dtype: int64

In [15]:
list=data_new.columns[data_new.isnull().sum()>0].tolist()
list.append('hospital_death')
#These columns need to be imputed based on linear regression. Possibilities must be checked.

In [16]:
matrix=data_new[list].corr()
matrix

,age,bmi,height,weight,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,hospital_death
age,1.000000,-0.087077,-0.109937,-0.127252,0.143167,0.076275,0.111017
bmi,-0.087077,1.000000,-0.056316,0.877339,-0.033546,-0.013796,-0.031247
height,-0.109937,-0.056316,1.000000,0.391967,-0.029071,-0.011588,-0.019526
weight,-0.127252,0.877339,0.391967,1.000000,-0.043706,-0.018303,-0.038362
apache_4a_hospital_death_prob,0.143167,-0.033546,-0.029071,-0.043706,1.000000,0.878988,0.311043
apache_4a_icu_death_prob,0.076275,-0.013796,-0.011588,-0.018303,0.878988,1.000000,0.283913
hospital_death,0.111017,-0.031247,-0.019526,-0.038362,0.311043,0.283913,1.000000

In [17]:
#As apache_4a_hospital_death_prob and apache_4a_icu_death_prob are highly correlated, removing apache_4a_icu_death_prob
data_new.drop('apache_4a_icu_death_prob',axis=1)

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal

In [18]:
#bmi= (weight/(height)^2)*10000
data_new[list].isnull().sum()

age                              4228
bmi                              3429
height                           1334
weight                           2720
apache_4a_hospital_death_prob    7947
apache_4a_icu_death_prob         7947
hospital_death                      0
dtype: int64

In [19]:
#Manual binarization of categorical variables before feature reduction
cat_dummy=pd.get_dummies(data_new[cat])
cat_dummy

,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,ethnicity_Other/Unknown,gender_F,gender_M,icu_admit_source_Accident & Emergency,icu_admit_source_Floor,...,apache_2_bodysystem_Cardiovascular,apache_2_bodysystem_Gastrointestinal,apache_2_bodysystem_Haematologic,apache_2_bodysystem_Metabolic,apache_2_bodysystem_Neurologic,apache_2_bodysystem_Renal/Genitourinary,apache_2_bodysystem_Respiratory,apache_2_bodysystem_Trauma,apache_2_bodysystem_Undefined Diagnoses,apache_2_bodysystem_Undefined diagnoses
0,0,0,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,0,0,1,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,0,0,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,0,0,0
91709,0,0,1,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,0
91710,0,0,1,0,0,0,0,1,1,0,...,0,0,0,1,0,0,0,0,0,0
91711,0,0,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
91712,0,0,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [20]:
#Concatenating dummy variables to the dataset
data_new= pd.concat([data_new,cat_dummy],axis=1,sort=False)
data_new

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,apache_2_bodysystem_Cardiovascular,apache_2_bodysystem_Gastrointestinal,apache_2_bodysystem_Haematologic,apache_2_bodysystem_Metabolic,apache_2_bodysystem_Neurologic,apache_2_bodysystem_Renal/Genitourinary,apache_2_bodysystem_Respiratory,apache_2_bodysystem_Trauma,apache_2_bodysystem_Undefined Diagnoses,apache_2_bodysystem_Undefined diagnoses
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,1,0,0,0,0,0,0,0,0,0
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0,0,0,0,0,0,1,0,0,0
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0,0,0,1,0,0,0,0,0,0
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,1,0,0,0,0,0,0,0,0,0
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,1,0,0,0,0,0,0,0,0,0
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,1,0,0,0,0,0,0,0,0,0
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0,0,0,1,0,0,0,0,0,0
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0,0,0,0,0,0,1,0,0,0
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0,1,0,0,0,0,0,0,0,0

In [21]:
#Dropping the original categorical variables to avoid multi collinearity
data_new=data_new.drop(data_new[cat].columns,axis=1)
data_new

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,...,apache_2_bodysystem_Cardiovascular,apache_2_bodysystem_Gastrointestinal,apache_2_bodysystem_Haematologic,apache_2_bodysystem_Metabolic,apache_2_bodysystem_Neurologic,apache_2_bodysystem_Renal/Genitourinary,apache_2_bodysystem_Respiratory,apache_2_bodysystem_Trauma,apache_2_bodysystem_Undefined Diagnoses,apache_2_bodysystem_Undefined diagnoses
0,66154,25312,118,0,68.0,22.730000,0,180.3,92,0.541667,...,1,0,0,0,0,0,0,0,0,0
1,114252,59342,81,0,77.0,27.420000,0,160.0,90,0.927778,...,0,0,0,0,0,0,1,0,0,0
2,119783,50777,118,0,25.0,31.950000,0,172.7,93,0.000694,...,0,0,0,1,0,0,0,0,0,0
3,79267,46918,118,0,81.0,22.640000,1,165.1,92,0.000694,...,1,0,0,0,0,0,0,0,0,0
4,92056,34377,33,0,19.0,NaN,0,188.0,91,0.073611,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,177.8,927,0.298611,...,1,0,0,0,0,0,0,0,0,0
91709,66119,13486,121,0,56.0,47.179671,0,183.0,925,0.120139,...,1,0,0,0,0,0,0,0,0,0
91710,8981,58179,195,0,48.0,27.236914,0,170.2,908,0.046528,...,0,0,0,1,0,0,0,0,0,0
91711,33776,120598,66,0,NaN,23.297481,0,154.9,922,0.081944,...,0,0,0,0,0,0,1,0,0,0
91712,1671,53612,104,0,82.0,22.031250,1,160.0,926,0.018056,...,0,1,0,0,0,0,0,0,0,0

In [22]:
from sklearn.linear_model import Lasso

In [23]:
#Splitting data to X and Y to perform Lasso regression
X= data_new.loc[:,~data_new.columns.isin(['hospital_death'])]
y= data_new['hospital_death']